### ISSUE TITLE
What's in a name?

### ISSUE THREAD

**Issue by adamashton** [ridernator/folly#1]
Hey,

Looking over your library it looks very good.
Can't help but wonder why you named it 'folly'. Makes me nervous about using it!

http://dictionary.reference.com/browse/folly

Thanks,
Adam

**Comment by ridernator** [comment]
Hi Adam,

I named it this because I wrote it to aid me in writing betting robots. Since none of my robots are ever profitable, I named the library "folly" as in the 3rd definition in the link : 

"a costly and foolish undertaking; unwise investment or expenditure."

I still write robots as a hobby but with no real hope of ever making any money from them

Ciaron

**Comment by adamashton** [comment]
Hi Ciaron,

Fair enough. 

Good luck with any future robots.. I hope to see the library name change some day! ;)

Adam
